<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Il2CppMetadataScanner</AssemblyName>
    <RootNamespace>Il2CppMetadataScanner</RootNamespace>
  </PropertyGroup>

</Project>
